name: google_play_clone
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 1.0.0
  
  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/neeel.png
    - assets/images/apps/1.png
    - assets/images/apps/2.png
    - assets/images/apps/3.png
    - assets/images/apps/4.png
    - assets/images/apps/5.png
    - assets/images/apps/6.png
    - assets/images/apps/7.png
    - assets/images/apps/8.png
    - assets/images/apps/9.png
    - assets/images/apps/10.png
    - assets/images/apps/11.png
    - assets/images/apps/12.png
    - assets/images/apps/13.png
    - assets/images/apps/14.png
    - assets/images/apps/15.png
    - assets/images/apps/16.png
    - assets/images/apps/17.png
    - assets/images/apps/18.png
    - assets/images/apps/19.png
    - assets/images/apps/20.png
    

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
